seed: -1

clip_observations: 5.0
clip_actions: 1.0

policy: # only works for MlpPolicy right now
  pi_hid_sizes: [1024, 512, 512]
  vf_hid_sizes: [1024, 512, 512]
  activation: elu # can be elu, relu, selu, crelu, lrelu, tanh, sigmoid
learn:
  agent_name: shadow_hand
  test: False
  resume: 0
  log_interval: 1000
  print_log: True

  # rollout params
  max_iterations: 100000

  # training params
  clip_param: 0.2
  entropy_coef: 0
  nsteps: 20
  num_learning_epochs: 10
  num_minibatches: 4 # this is per agent
  max_grad_norm: 1
  optim_stepsize: 3.e-4 # 3e-4 is default for single agent training with constant schedule
  schedule: adaptive # could be adaptive or linear or fixed
  desired_kl: 0.016
  gamma: 0.99
  lam: 0.95
  init_noise_std: 1.0
