defaults:
  - ../default

task_name: "dmcontrol:walker_stand"
robot_name: "none"  # dm_control tasks don't use robot configs

algo: "td3"

observation_space:
  shape: [24]
observation_shape: [24]

td3:
  action_num: 6
  multi_gpu: ${experiment.multi_gpu}
  num_actors: ${environment.num_envs}

  # Network architecture
  network:
    mlp:
      units: [512, 512, 256]

  # Hyperparameters
  learning_rate: 3e-4
  critic_learning_rate: 3e-4
  lr_schedule: "adaptive"
  kl_threshold: 0.016
  batch_size: 256
  replay_buffer_size: 1000000
  gamma: 0.99
  tau: 0.005

  # TD3 specific
  policy_noise: 0.2
  noise_clip: 0.5
  policy_delay: 2
  exploration_noise: 0.1

  # Training schedule
  max_epochs: 10000
  max_agent_steps: 10000000
  steps_num: 256
  games_per_epoch: 10
  warmup_steps: 25000
  learning_starts: 25000

  # Logging and saving
  save_frequency: 50
  save_best_after: 50
  log_interval: 100
  eval_interval: 1000
  reward_threshold: 5000

  # Normalization
  normalize_input: True
  normalize_value: False
  normalize_reward: True
  reward_scale_value: 1.0

  # Gradient clipping
  truncate_grads: True
  grad_norm: 1.0
