seed: -1

clip_observations: 5.0
clip_actions: 1.0

policy: # only works for MlpPolicy right now
  pi_hid_sizes: [1024, 1024, 512]
  q_hid_sizes: [1024, 1024, 512]
  activation: elu # can be elu, relu, selu, crelu, lrelu, tanh, sigmoid
  encoder_type: "cnn"
  fix_img_encoder: True # if True, the image encoder will not be trained, useful for transfer learning
  fix_actor_img_encoder: True # if True, the image encoder in the actor will not be trained, useful for transfer learning
learn:
  agent_name: shadow_hand
  test: False
  resume: 0
  log_interval: 10000
  print_log: True

  # rollout params
  max_iterations: 100000

  # training params
  max_grad_norm: 1
  actor_lr: 1.e-4 # 3e-4 is default for single agent training with constant schedule
  critic_lr: 1.e-4
  tau: 0.005
  alpha: 0.2
  policy_frequency: 1
  target_network_frequency: 2
  batch_size: 4096
  prefill: 100000
  buffer_size: 5000
  gamma: 0.96
