# IsaacGym Stand Task Configuration
# Inherits from base.yaml

# -------------------------------------------------------------------------------
# Environment
# -------------------------------------------------------------------------------
sim: "isaacgym"
robots: ["h1"]
task: "stand"
