# MJX Stand Task Configuration
# Inherits from base.yaml

# -------------------------------------------------------------------------------
# Environment
# -------------------------------------------------------------------------------
sim: "mjx"
robots: ["franka"]
task: "stand"
