# MJX Run Task Configuration
# Inherits from base.yaml

# -------------------------------------------------------------------------------
# Environment
# -------------------------------------------------------------------------------
sim: "mjx"
robots: ["h1"]
task: "stair"
total_timesteps: 10000
